app:
    resource: "@AppBundle/Controller/"
    type:     annotation
# site:
#     path:      /base
#     defaults:  { _controller: AppBundle:Site:index }
index:
    path:      /index
    defaults:  { _controller: AppBundle:Home:index }
home:
    path:      /
    defaults:  { _controller: AppBundle:Home:index }
resume:
    path:      /resume
    defaults:  { _controller: AppBundle:Resume:display}
    methods:   [GET]
contact:
    path:      /contact
    defaults:  { _controller: AppBundle:Contact:display}
    methods:   [GET]
software:
    path:      /software
    defaults:  { _controller: AppBundle:Software:display}
    methods:   [GET]
